FROM n8nio/n8n:latest

# Accept build-time arguments
ARG USERNAME
ARG PASSWORD

# Authentication
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=${USERNAME}
ENV N8N_BASIC_AUTH_PASSWORD=${PASSWORD}

# Required for Railway
ENV N8N_PORT=5678
ENV N8N_HOST=0.0.0.0
EXPOSE 5678

# Optional fixes
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

# Start n8n
CMD ["n8n"]
